name: attends_trecker
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.20.1
  chips_choice: ^3.0.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  cupertino_icons: ^1.0.6
  shared_preferences: ^2.3.3 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.1.5  # Required for code generation
  hive_generator: ^1.1.1  # Required to generate adapter code for Hive
  

flutter:
  uses-material-design: true
